### ISSUE TITLE
Cordova build error

### ISSUE THREAD

**Issue by drewgillies** [Microsoft/vsts-cordova-tasks#66]
Re-routed from here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/0a3f308f-40c2-4fc8-995e-350394e829f8/cordova-build-error?forum=tfsgeneral

Hello,

When attempting to use VSTS Cordova build task, I get the following error:

FAILURE: Build failed with an exception.* 
What went wrong:A problem occurred configuring root project 'android'.
> java.lang.NullPointerException (no error message)

What steps do you suggest I take to resolve this?

Thanks

**Comment by jln1989** [comment]
@drewgillies : We had the same issue and you need to configure the ANDROID_HOME and JAVA_HOME properly. Can you let me know if you are getting this error in any of the hosted agents? If the hosted agent build is running without any issue, it means the configuration in the local agent is the root cause most probably.

**Comment by drewgillies** [comment]
I'm going to go ahead and close this, now that we have a documented fix above. Any concerns, let me know.
